"use client";
import Image from "next/image";
import { useState, type ReactNode } from "react";
import { Anchor, ArrowRight, Clock3, Mail, MapPin, Menu, Phone, ShieldCheck, ShipWheel, X } from "lucide-react";
import { company } from "@/content/company";
import { ContactForm } from "@/components/contact-form";

const nav = [["Home", "home"], ["About", "about"], ["Services", "services"], ["Why Us", "why-us"], ["Contact", "contact"]] as const;
function LinkButton({ href, children, secondary = false }: { href: string; children: ReactNode; secondary?: boolean }) { return <a className={secondary ? "button secondary" : "button"} href={href}>{children} <ArrowRight size={17} /></a>; }
export default function Home() {
  const [open, setOpen] = useState(false); const address = company.address.join(", ");
  return <><a className="skip" href="#main">Skip to content</a><header className="header"><a href="#home" className="brand" aria-label="Landseaire Logistics Co. home"><Image src="/brand/landseaire-logo.png" alt="Landseaire Logistics Co." width={520} height={230} priority /></a><nav className={open ? "nav open" : "nav"} aria-label="Main navigation">{nav.map(([label, id]) => <a onClick={() => setOpen(false)} href={`#${id}`} key={id}>{label}</a>)}<a className="nav-cta" href="#contact" onClick={() => setOpen(false)}>Request Assistance</a></nav><button className="menu" onClick={() => setOpen(!open)} aria-label={open ? "Close navigation menu" : "Open navigation menu"} aria-expanded={open}>{open ? <X /> : <Menu />}</button></header>
    <main id="main"><section id="home" className="hero"><div className="hero-copy"><p className="eyebrow"><ShipWheel size={17} /> Philippine port agency & logistics</p><h1>Shipping and Logistics Support You Can Depend On</h1><p className="lead">Professional port agency, customs brokerage, freight forwarding, ship-spare delivery, and specialized logistics solutions for domestic and international operations.</p><div className="actions"><LinkButton href="#contact">Request Logistics Assistance</LinkButton><LinkButton href="#services" secondary>View Our Services</LinkButton></div><p className="availability"><Clock3 size={18} /> Operational assistance available 24 hours a day, 365 days a year.</p></div><div className="hero-mark"><div className="route-grid"><span>Philippine ports</span><span>Worldwide logistics</span><strong>Land. Sea. Air.</strong></div></div></section>
    <section className="intro"><p className="eyebrow">Landseaire Logistics Co.</p><h2>Experienced support for every operational detail.</h2><p>Established in August 2026, Landseaire Logistics Co. brings together experienced shipping and logistics professionals and strong partnerships to support foreign and local vessels engaged in Philippine international trade, as well as domestic and international logistics clients.</p></section>
    <section id="about" className="section split"><div><p className="eyebrow">About us</p><h2>Close to Manila’s key transport gateways.</h2><p>Based in Intramuros, Manila, our office offers convenient access to Manila’s seaport and airport areas. We focus on prompt communication and practical, cost-effective support for a wide range of client needs.</p></div><div className="statement"><div><span>Mission</span><p>“{company.mission}”</p></div><div><span>Vision</span><p>“{company.vision}”</p></div></div></section>
    <section id="services" className="section services"><p className="eyebrow">Our services</p><h2>Port agency and logistics support, clearly coordinated.</h2><div className="service-grid">{company.services.map(([name, description], i) => <article className="service-card" key={name}><span>{String(i + 1).padStart(2, "0")}</span><h3>{name}</h3><p>{description}</p><Anchor size={21} aria-hidden="true" /></article>)}</div></section>
    <section id="why-us" className="section why"><div><p className="eyebrow">Why Landseaire</p><h2>Built for responsive, individualized service.</h2></div><ul>{["Industry-experienced team and strong professional partnerships", "Personalized, cost-effective logistics solutions", "24/7 operational availability for prompt communication", "Strategic Intramuros, Manila location", "Domestic and international logistics support", "Specialized vessel documentation and operational assistance"].map(item => <li key={item}><ShieldCheck size={21} />{item}</li>)}</ul></section>
    <section id="contact" className="section contact"><div className="contact-intro"><p className="eyebrow">Request assistance</p><h2>Tell us what your operation needs.</h2><p>Share the details and the Landseaire team can respond through your preferred contact method.</p><div className="contact-links"><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`} target="_blank" rel="noopener noreferrer"><MapPin />{company.address.map(line => <span key={line}>{line}</span>)}</a><a href="tel:09173222571"><Phone />0917 322 2571</a><a href="mailto:ampatiag71@gmail.com"><Mail />ampatiag71@gmail.com</a><a className="whatsapp" href="https://wa.me/639472051903" target="_blank" rel="noopener noreferrer">WhatsApp: 0947 205 1903</a></div><p className="hours"><Clock3 size={18} /> Operational assistance is available 24/7. Office correspondence can be sent to the contacts listed here.</p></div><div className="form-panel"><ContactForm /></div></section>
    <section className="final"><div><p className="eyebrow">Ready to coordinate?</p><h2>Reliable support begins with a clear conversation.</h2></div><LinkButton href="#contact">Request Logistics Assistance</LinkButton></section></main>
    <footer><div><Image src="/brand/landseaire-logo.png" alt="Landseaire Logistics Co." width={260} height={115} /><p>{company.approvedTagline}</p></div><div><h3>Contact</h3><p>{company.address.map(x => <span key={x}>{x}<br /></span>)}</p><a href={`mailto:${company.businessEmail}`}>{company.businessEmail}</a><small>Business email listed in the official profile; confirmation required.</small></div><div><h3>Key contacts</h3>{company.contacts.map(c => <p key={c.name}><strong>{c.name}</strong><br />{c.role}<br /><a href={`tel:${c.mobile}`}>{c.mobile.replace(/(\d{4})(\d{3})(\d{4})/, "$1 $2 $3")}</a></p>)}</div></footer></>;
}
