"use client";
import Image from "next/image";
import { useEffect, useState, type ReactNode } from "react";
import { Anchor, ArrowRight, Check, Clock3, Mail, MapPin, Menu, Phone, ShipWheel, X } from "lucide-react";
import { company } from "@/content/company";
import { ContactForm } from "@/components/contact-form";
import { Reveal } from "@/components/reveal";
const nav = [["Home", "home"], ["About", "about"], ["Services", "services"], ["Why Us", "why-us"], ["Contact", "contact"]] as const;
const assetBasePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
function LinkButton({ href, children, secondary = false }: { href: string; children: ReactNode; secondary?: boolean }) { return <a className={secondary ? "button secondary" : "button"} href={href}>{children}<ArrowRight size={17} /></a>; }
export default function Home() { const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const address = company.address.join(", "); useEffect(() => { const listener = () => setScrolled(window.scrollY > 24); listener(); window.addEventListener("scroll", listener, { passive: true }); return () => window.removeEventListener("scroll", listener); }, []);
return <><a className="skip" href="#main">Skip to content</a><header className={`header ${scrolled ? "scrolled" : ""}`}><a href="#home" className="brand" aria-label="Landseaire Logistics Co. home"><Image src={`${assetBasePath}/brand/landseaire-logo.png`} alt="Landseaire Logistics Co." width={520} height={230} priority /></a><nav className={open ? "nav open" : "nav"} aria-label="Main navigation">{nav.map(([label,id])=><a onClick={()=>setOpen(false)} href={`#${id}`} key={id}>{label}</a>)}<a className="nav-cta" href="#contact" onClick={()=>setOpen(false)}>Request Assistance</a></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label={open?"Close navigation menu":"Open navigation menu"} aria-expanded={open}>{open?<X/>:<Menu/>}</button></header>
<main id="main"><section id="home" className="hero"><Image className="hero-image" src={`${assetBasePath}/images/hero-port.png`} alt="Cargo vessel and container port supporting maritime logistics" fill priority sizes="100vw" /><div className="hero-overlay"/><div className="hero-copy"><p className="eyebrow hero-in one"><ShipWheel size={17}/>Philippine port agency & logistics</p><h1 className="hero-in two">Shipping and Logistics Support You Can Depend On</h1><p className="lead hero-in three">Professional port agency, customs brokerage, freight forwarding, ship-spare delivery, and specialized logistics solutions for domestic and international operations.</p><div className="actions hero-in four"><LinkButton href="#contact">Request Logistics Assistance</LinkButton><LinkButton href="#services" secondary>View Our Services</LinkButton></div><p className="availability hero-in five"><Clock3 size={18}/>Operational assistance available 24 hours a day, 365 days a year.</p></div><svg className="route" viewBox="0 0 800 180" aria-hidden="true"><path d="M0 130C170 15 260 205 420 80S650 10 800 80"/><circle cx="420" cy="80" r="5"/></svg></section>
<Reveal className="intro"><p className="eyebrow">Landseaire Logistics Co.</p><h2>Experienced support for every operational detail.</h2><p>Established in August 2026, Landseaire Logistics Co. brings together experienced shipping and logistics professionals and strong partnerships to support foreign and local vessels engaged in Philippine international trade, as well as domestic and international logistics clients.</p></Reveal>
<section id="about" className="section split"><Reveal><p className="eyebrow">About us</p><h2>Close to Manila’s key transport gateways.</h2><p>Based in Intramuros, Manila, our office offers convenient access to Manila’s seaport and airport areas. We focus on prompt communication and practical, cost-effective support for a wide range of client needs.</p></Reveal><Reveal className="statement" delay={100}><div><span>Mission</span><p>“{company.mission}”</p></div><div><span>Vision</span><p>“{company.vision}”</p></div></Reveal></section>
<section className="process"><Reveal><p className="eyebrow">How we coordinate</p><h2>A clear route from request to support.</h2></Reveal><div className="process-grid">{["Share your operational requirements", "Coordinate the right agency or logistics support", "Stay informed through clear communication"].map((step,i)=><Reveal key={step} delay={i*70} className="process-step"><span>0{i+1}</span><p>{step}</p></Reveal>)}</div></section>
<section id="services" className="section services"><Reveal><p className="eyebrow">Our services</p><h2>Port agency and logistics support, clearly coordinated.</h2></Reveal><div className="service-grid">{company.services.map(([name,description],i)=><Reveal key={name} delay={i*65}><article className="service-card"><span>{String(i+1).padStart(2,"0")}</span><Anchor size={22} aria-hidden="true"/><h3>{name}</h3><p>{description}</p><ArrowRight className="card-arrow" size={20} aria-hidden="true"/></article></Reveal>)}</div></section>
<section id="why-us" className="section why"><Reveal><p className="eyebrow">Why Landseaire</p><h2>Built for responsive, individualized service.</h2></Reveal><Reveal delay={100}><ul>{["Industry-experienced team and strong professional partnerships", "Personalized, cost-effective logistics solutions", "24/7 operational availability for prompt communication", "Strategic Intramuros, Manila location", "Domestic and international logistics support", "Specialized vessel documentation and operational assistance"].map(item=><li key={item}><Check size={20}/>{item}</li>)}</ul></Reveal></section>
<section id="contact" className="section contact"><Reveal><p className="eyebrow">Request assistance</p><h2>Tell us what your operation needs.</h2><p>Share the details and the Landseaire team can respond through your preferred contact method.</p><div className="contact-links"><a className="address-card" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`} target="_blank" rel="noopener noreferrer"><MapPin/><span><strong>Visit our Manila office</strong><span>3rd Floor, Laiko Building</span><span>372 Cabildo Street, Intramuros</span><span>Manila, Philippines 1002</span><em>Open in Google Maps →</em></span></a><a href="tel:09173222571"><Phone/>0917 322 2571</a><a href="mailto:ampatiag71@gmail.com"><Mail/>ampatiag71@gmail.com</a><a className="whatsapp" href="https://wa.me/639472051903" target="_blank" rel="noopener noreferrer">WhatsApp: 0947 205 1903</a></div><p className="hours"><Clock3 size={18}/>Operational assistance is available 24/7.</p></Reveal><Reveal className="form-panel" delay={100}><ContactForm/></Reveal></section>
<section className="final"><div><p className="eyebrow">Ready to coordinate?</p><h2>Reliable support begins with a clear conversation.</h2></div><LinkButton href="#contact">Request Logistics Assistance</LinkButton></section></main>
<footer><div><Image src={`${assetBasePath}/brand/landseaire-logo.png`} alt="Landseaire Logistics Co." width={260} height={115}/></div><div><h3>Contact</h3><p>{company.address.map(x=><span key={x}>{x}<br/></span>)}</p><a href={`mailto:${company.businessEmail}`}>{company.businessEmail}</a></div><div className="social"><h3>Connect with us</h3><div className="social-icons" aria-label="Social media"><span title="Facebook" aria-label="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3.2 0-5 1.9-5 5.2V12H6v4h3v5h4v-5h3.2l.8-4H13V9.5c0-1 .5-1.5 1-1.5Z"/></svg></span><span title="LinkedIn" aria-label="LinkedIn"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 8.3H3V21h3.5V8.3ZM4.8 3A2 2 0 1 0 4.8 7a2 2 0 0 0 0-4ZM21 13.7c0-3.8-2-5.6-4.7-5.6-2.2 0-3.2 1.2-3.8 2v-1.8H9V21h3.5v-6.3c0-1.7.3-3.3 2.4-3.3 2 0 2.1 1.9 2.1 3.4V21H21v-7.3Z"/></svg></span></div></div></footer></>; }
