"use client";
import Image from "next/image";
import { useEffect, useState, type ReactNode } from "react";
import { Anchor, ArrowRight, Check, ClipboardCheck, Clock3, FileText, Handshake, Mail, MapPin, Menu, PackageCheck, Phone, ShipWheel, Truck, Wrench, X } from "lucide-react";
import { company } from "@/content/company";
import { ContactForm } from "@/components/contact-form";
import { Reveal } from "@/components/reveal";
const nav = [["Home", "home"], ["About", "about"], ["Services", "services"], ["Why Us", "why-us"], ["Contact", "contact"]] as const;
const serviceIcons = [PackageCheck, FileText, Truck, ShipWheel, Wrench, ClipboardCheck, Handshake] as const;
const assetBasePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
function LinkButton({ href, children, secondary = false }: { href: string; children: ReactNode; secondary?: boolean }) { return <a className={secondary ? "button secondary" : "button"} href={href}>{children}<ArrowRight size={17} /></a>; }
function ServiceCardIcon({ index }: { index: number }) { const Icon = serviceIcons[index] ?? Anchor; return <Icon className="service-icon" size={24} aria-hidden="true" />; }
export default function Home() { const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [activeSection, setActiveSection] = useState("home"); const address = company.address.join(", "); useEffect(() => { const listener = () => setScrolled(window.scrollY > 24); listener(); window.addEventListener("scroll", listener, { passive: true }); return () => window.removeEventListener("scroll", listener); }, []); useEffect(() => { const sections = nav.map(([, id]) => document.getElementById(id)).filter((section): section is HTMLElement => section !== null); const observer = new IntersectionObserver((entries) => { const current = entries.filter(entry => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (current) setActiveSection(current.target.id); }, { rootMargin: "-35% 0px -55% 0px", threshold: [0.1, 0.35, 0.6] }); sections.forEach(section => observer.observe(section)); return () => observer.disconnect(); }, []);
return <><a className="skip" href="#main">Skip to content</a><header className={`header ${scrolled ? "scrolled" : ""}`}><a href="#home" className="brand" aria-label="Landseaire Logistics Co. home"><Image src={`${assetBasePath}/brand/landseaire-logo.png`} alt="Landseaire Logistics Co." width={520} height={230} priority /></a><nav className={open ? "nav open" : "nav"} aria-label="Main navigation">{nav.map(([label,id])=><a onClick={()=>{ setOpen(false); setActiveSection(id); }} href={`#${id}`} key={id} className={activeSection === id ? "active" : undefined} aria-current={activeSection === id ? "page" : undefined}>{label}</a>)}<a className="nav-cta" href="#contact" onClick={()=>setOpen(false)}>Request Assistance</a></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label={open?"Close navigation menu":"Open navigation menu"} aria-expanded={open}>{open?<X/>:<Menu/>}</button></header>
<main id="main"><section id="home" className="hero"><Image className="hero-image" src={`${assetBasePath}/images/hero-port.png`} alt="Cargo vessel and container port supporting maritime logistics" fill priority sizes="100vw" /><div className="hero-overlay"/><div className="hero-copy"><p className="eyebrow hero-in one"><ShipWheel size={17}/>Port agency and logistics services</p><h1 className="hero-in two">Expert port agency services and comprehensive logistics solutions.</h1><p className="lead hero-in three">We provide expert port agency services for foreign and local vessels in Philippine international trade, alongside comprehensive logistics solutions for domestic and international clients.</p><div className="actions hero-in four"><LinkButton href="#contact">Contact Our Team</LinkButton><LinkButton href="#services" secondary>View Our Services</LinkButton></div><p className="availability hero-in five"><Clock3 size={18}/>Our team is on hand 24 hours a day, every day of the year.</p></div><svg className="route" viewBox="0 0 800 180" aria-hidden="true"><path d="M0 130C170 15 260 205 420 80S650 10 800 80"/><circle cx="420" cy="80" r="5"/></svg></section>
<Reveal className="intro"><p className="eyebrow">Landseaire Logistics Co.</p><h2>Experienced shipping and logistics professionals.</h2><p>Established in August 2026, our team brings many years of experience in the shipping and logistics industries, built through strong partnerships and the dedicated efforts of long-time industry professionals.</p></Reveal>
<section id="about" className="section split"><Reveal><p className="eyebrow">About us</p><h2>Convenient access to Manila’s seaport and airport areas.</h2><p>Landseaire Logistics Co. is located on the 3rd Floor of the Laiko Building, 372 Cabildo St., Intramuros, Manila. We are dedicated to providing expert port agency services for foreign and local vessels in Philippine international trade, alongside comprehensive logistics solutions for domestic and international clients.</p></Reveal><Reveal className="statement" delay={100}><div><span>Mission</span><p>“{company.mission}”</p></div><div><span>Vision</span><p>“{company.vision}”</p></div></Reveal></section>
<section id="services" className="section services"><Reveal><p className="eyebrow">Our services</p><h2>Agency, brokerage and freight forwarding services.</h2></Reveal><div className="service-grid">{company.services.map(([name,description],i)=><Reveal key={name} delay={i*65}><article className="service-card"><span>{String(i+1).padStart(2,"0")}</span><ServiceCardIcon index={i}/><h3>{name}</h3><p>{description}</p><ArrowRight className="card-arrow" size={20} aria-hidden="true"/></article></Reveal>)}</div></section>
<section id="why-us" className="section why"><Reveal><p className="eyebrow">Why Landseaire</p><h2>Dependable and cost-effective logistics support.</h2></Reveal><Reveal delay={100}><ul>{["Many years of experience in the shipping and logistics industries", "Strong partnerships and long-time industry professionals", "Personalized solutions for the specific needs of clients", "Quick, accurate and effective communication", "Support for domestic and international clients", "Convenient access to Manila’s seaport and airport areas"].map(item=><li key={item}><Check size={20}/>{item}</li>)}</ul></Reveal></section>
<section id="contact" className="section contact"><Reveal><p className="eyebrow">Contact us</p><h2>Port agency, brokerage and freight forwarding services.</h2><p>Contact our team for agency, brokerage and freight forwarding services.</p><div className="contact-links"><a className="address-card" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`} target="_blank" rel="noopener noreferrer"><MapPin/><span><strong>Visit our Manila office</strong><span>3rd Floor, Laiko Building</span><span>372 Cabildo Street, Intramuros</span><span>Manila, Philippines 1002</span><em>Open in Google Maps →</em></span></a><a href="tel:09173222571"><Phone/>0917 322 2571</a><a href="mailto:ampatiag71@gmail.com"><Mail/>ampatiag71@gmail.com</a><a className="whatsapp" href="https://wa.me/639472051903" target="_blank" rel="noopener noreferrer">WhatsApp: 0947 205 1903</a></div><p className="hours"><Clock3 size={18}/>Our team is on hand 24 hours a day, every day of the year.</p></Reveal><Reveal className="form-panel" delay={100}><ContactForm/></Reveal></section></main>
<footer><div><Image src={`${assetBasePath}/brand/landseaire-logo.png`} alt="Landseaire Logistics Co." width={260} height={115}/></div><div><h3>Contact</h3><p>{company.address.map(x=><span key={x}>{x}<br/></span>)}</p><a href={`mailto:${company.businessEmail}`}>{company.businessEmail}</a></div><div className="social"><h3>Connect with us</h3><div className="social-icons" aria-label="Social media"><span title="Facebook" aria-label="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3.2 0-5 1.9-5 5.2V12H6v4h3v5h4v-5h3.2l.8-4H13V9.5c0-1 .5-1.5 1-1.5Z"/></svg></span><span title="LinkedIn" aria-label="LinkedIn"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 8.3H3V21h3.5V8.3ZM4.8 3A2 2 0 1 0 4.8 7a2 2 0 0 0 0-4ZM21 13.7c0-3.8-2-5.6-4.7-5.6-2.2 0-3.2 1.2-3.8 2v-1.8H9V21h3.5v-6.3c0-1.7.3-3.3 2.4-3.3 2 0 2.1 1.9 2.1 3.4V21H21v-7.3Z"/></svg></span></div></div></footer></>; }
